In [1]:
import pandas as pd

# Importing main source of games information

In [2]:
game = pd.read_csv('data/game.csv')

In [3]:
type(game)

pandas.core.frame.DataFrame

In [4]:
game

,Title,Features.Handheld?,Features.Max Players,Features.Multiplatform?,Features.Online?,Metadata.Genres,Metadata.Licensed?,Metadata.Publishers,Metadata.Sequel?,Metrics.Review Score,...,Length.Main + Extras.Average,Length.Main + Extras.Leisure,Length.Main + Extras.Median,Length.Main + Extras.Polled,Length.Main + Extras.Rushed,Length.Main Story.Average,Length.Main Story.Leisure,Length.Main Story.Median,Length.Main Story.Polled,Length.Main Story.Rushed
0,Super Mario 64 DS,True,1,True,True,Action,True,Nintendo,True,85,...,24.916667,29.966667,25.000000,16,18.333333,14.333333,18.316667,14.500000,21,9.700000
1,Lumines: Puzzle Fusion,True,1,True,True,Strategy,True,Ubisoft,True,89,...,9.750000,9.866667,9.750000,2,9.616667,10.333333,11.083333,10.000000,3,9.583333
2,WarioWare Touched!,True,2,True,True,"Action,Racing / Driving,Sgameports",True,Nintendo,True,81,...,3.850000,5.666667,3.333333,11,2.783333,1.916667,2.933333,1.833333,30,1.433333
3,Hot Shots Golf: Open Tee,True,1,True,True,Sports,True,Sony,True,81,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
4,Spider-Man 2,True,1,True,True,Action,True,Activision,True,61,...,12.766667,17.316667,12.500000,12,10.483333,8.350000,11.083333,8.000000,23,5.333333
5,The Urbz: Sims in the City,True,1,True,True,Simulation,True,EA,True,67,...,20.833333,25.200000,20.000000,3,16.450000,15.500000,15.750000,15.500000,2,15.250000
6,Ridge Racer,True,1,True,True,Racing / Driving,True,Namco,True,88,...,0.883333,0.933333,0.883333,2,0.833333,0.616667,0.783333,0.533333,3,0.450000
7,Metal Gear Ac!d,True,1,True,True,Strategy,True,Konami,True,75,...,24.833333,27.483333,25.100000,6,21.916667,20.700000,23.600000,20.783333,11,17.883333
8,Madden NFL 2005,True,1,True,True,Sports,True,EA,True,68,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
9,Pokmon Dash,True,1,True,True,Racing / Driving,True,Nintendo,True,46,...,0.000000,0.000000,0.000000,0,0.000000,1.116667,1.200000,1.083333,3,1.050000
10,Dynasty Warriors,True,1,True,True,"Action,Adventure,Role-Playing (RPG)",True,NaN,True,62,...,0.000000,0.000000,0.000000,0,0.000000,8.883333,18.050000,2.083333,4,3.116667
11,Feel the Magic XY/XX,True,1,True,True,"Action,Adventure,Racing / Driving,Sports",True,Sega,True,75,...,3.100000,3.150000,3.100000,2,3.050000,2.850000,3.783333,2.983333,7,2.300000
12,Ridge Racer DS,True,1,True,True,Racing / Driving,True,Namco,True,63,...,0.000000,0.000000,0.000000,0,0.000000,2.233333,2.233333,2.233333,1,2.233333
13,Darkstalkers Chronicle: The Chaos Tower,True,1,True,True,Action,True,Capcom,True,74,...,0.000000,0.000000,0.000000,0,0.000000,1.633333,2.400000,2.000000,7,1.066667
14,Ape Escape Academy,True,4,True,True,"Action,Sports",True,Sony,True,51,...,0.000000,0.000000,0.000000,0,0.000000,1.883333,1.883333,1.883333,1,1.883333
15,Polarium,True,1,True,True,Strategy,True,Nintendo,True,73,...,0.000000,0.000000,0.000000,0,0.000000,5.416667,5.783333,5.750000,4,4.866667
16,Asphalt: Urban GT,True,1,True,True,"Racing / Driving,Simulation",True,Ubisoft,True,60,...,0.000000,0.000000,0.000000,0,0.000000,15.000000,15.000000,15.000000,1,15.000000
17,Zoo Keeper,True,1,True,True,Action,True,NaN,True,74,...,0.000000,0.000000,0.000000,0,0.000000,6.000000,7.750000,5.000000,4,4.750000
18,Mr. DRILLER: Drill Spirits,True,1,True,True,Action,True,Namco,True,72,...,0.000000,0.000000,0.000000,0,0.000000,9.883333,10.983333,9.883333,2,8.766667
19,Sprung,True,1,True,True,Adventure,True,Ubisoft,True,48,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
20,Armored Core: Formula Front - Extreme Battle,True,1,True,True,"Action,Strategy",True,NaN,True,66,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
21,Puyo Pop Fever,True,1,True,True,"Action,Strategy",True,Sega,True,76,...,4.000000,4.000000,4.000000,1,4.000000,1.750000,1.866667,1.750000,2,1.616667
22,Mario Kart DS,True,1,True,True,Racing / Driving,True,Nintendo,True,91,...,10.716667,15.166667,10.000000,24,7.800000,4.783333,7.366667,4.500000,35,3.066667
23,Nintendogs,True,1,True,True,Simulation,True,Nintendo,True,83,...,43.350000,49.016667,43.350000,2,37.666667,27.966667,46.816667,22.150000,6,18.533333
24,Brain Age: Train Your Brain in Minutes a Day!,True,1,True,True,Action,True,Nintendo,True,77,...,0.933333,0.966667,0.933333,2,0.900000,0.933333,1.483333,1.000000,6,0.633333
25,Brain Agey: More Training in Minutes a Day!,True,1,True,True,Action,True,Nintendo,True,77,...,23.333333,29.583333,15.000000,3,17.083333,7.266667,12.066667,1.000000,3,2.483333
26,Grand Theft Auto: Liberty City Stories,True,1,True,True,"Action,Racing / Driving",True,"Capcom,Rockstar",True,88,...,26.550000,39.133333,20.000000,11,18.633333,14.216667,21.900000,13.850000,42,10.533333
27,Animal Crossing: Wild World,True,1,True,True,Simulation,True,Nintendo,True,86,...,180.533333,265.133333,180.000000,9,105.133333,72.383333,135.583333,70.000000,11,45.583333
28,Big Brain Academy,True,1,True,True,Action,True,Nintendo,True,74,...,8.066667,8.533333,8.066667,2,7.600000,4.300000,5.350000,5.116667,4,2.850000
29,Call of Duty 2,True,4,True,True,Action,True,"Activision,Konami",True,89,...,9.600000,11.316667,10.000000,25,7.400000,8.516667,11.366667,8.983333,146,6.366667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1182,Harvey Birdman: Attorney at Law,True,1,True,True,Adventure,True,Capcom,True,62,...,0.000000,0.000000,0.000000,0,0.000000,3.850000,4.266667,3.750000,10,3.483333
1183,Secret Agent Clank,True,1,True,True,Action,True,Sony,True,72,...,7.850000,9.050000,8.000000,7,6.983333,7.716667,8.800000,7.500000,14,6.666667
1184,Space Invaders Extreme,True,1,True,True,Action,True,SquareEnix,True,84,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1185,Armored Core: For Answer,True,1,True,True,Action,True,Ubisoft,True,62,...,17.266667,19.433333,18.500000,5,14.866667,10.250000,12.533333,9.933333,5,8.716667
1186,Legendary,True,1,True,True,Action,True,Atari,True,50,...,7.600000,10.016667,6.500000,11,5.583333,5.283333,6.483333,5.000000,41,4.566667
1187,Agatha Christie: Evil Under the Sun,True,1,True,True,Adventure,True,NaN,True,46,...,0.000000,0.000000,0.000000,0,0.000000,9.250000,9.250000,9.250000,1,9.250000
1188,Agatha Christie: And Then There Were None,True,1,True,True,Adventure,True,NaN,True,50,...,0.000000,0.000000,0.000000,0,0.000000,7.166667,7.916667,7.500000,4,6.250000
1189,Armored Core: For Answer,True,1,True,True,Action,True,Ubisoft,True,64,...,17.266667,19.433333,18.500000,5,14.866667,10.250000,12.533333,9.933333,5,8.716667
1190,Cradle of Rome,True,1,True,True,Strategy,True,NaN,True,63,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1191,The Dark Spire,True,1,True,True,"Adventure,Role-Playing (RPG)",True,NaN,True,69,...,76.816667,95.216667,76.816667,2,58.400000,27.916667,27.916667,27.916667,1,27.916667
1192,"Flower, Sun and Rain",True,1,True,True,Adventure,True,NaN,True,54,...,8.816667,8.983333,8.816667,2,8.633333,11.916667,14.966667,8.000000,3,8.866667
1193,Insecticide,True,1,True,True,"Action,Adventure",True,NaN,True,55,...,3.083333,3.666667,2.600000,3,2.500000,3.700000,4.350000,3.700000,11,2.850000
1194,Izuna 2: The Unemployed Ninja Returns,True,1,True,True,Role-Playing (RPG),True,NaN,True,65,...,0.000000,0.000000,0.000000,0,0.000000,13.250000,13.250000,13.250000,1,13.250000
1195,Looney Tunes: Cartoon Conductor,True,1,True,True,Action,True,Eidos,True,67,...,0.000000,0.000000,0.000000,0,0.000000,4.000000,4.000000,4.000000,1,4.000000
1196,Nanostray 2,True,1,True,True,Action,True,NaN,True,75,...,0.000000,0.000000,0.000000,0,0.000000,3.000000,3.000000,3.000000,1,3.000000
1197,Hellboy: The Science of Evil,True,1,True,True,Action,True,Konami,True,42,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1198,Pipe Mania,True,1,True,True,Strategy,True,NaN,True,74,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1199,UEFA Euro 2008,True,1,True,True,Sports,True,EA,True,68,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1200,Vampire Rain,True,1,True,True,Action,True,NaN,True,30,...,0.000000,0.000000,0.000000,0,0.000000,10.883333,11.666667,10.500000,3,10.083333
1201,Baroque,True,1,True,True,"Action,Role-Playing (RPG)",True,NaN,True,50,...,0.000000,0.000000,0.000000,0,0.000000,7.783333,10.383333,7.783333,2,5.183333
1202,Supreme Commander,True,1,True,True,Strategy,True,NaN,True,56,...,26.266667,30.516667,25.850000,5,20.516667,19.600000,27.150000,19.000000,13,16.150000
1203,Hail to the Chimp,True,4,True,True,"Action,Strategy",True,NaN,True,52,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1204,Assassin's Creed: Altar's Chronicles,True,1,True,True,Action,True,Ubisoft,True,58,...,4.516667,4.616667,4.500000,3,4.416667,5.183333,7.033333,5.000000,14,4.200000
1205,The Legend of Kage 2,True,1,True,True,Action,True,SquareEnix,True,70,...,0.000000,0.000000,0.000000,0,0.000000,3.333333,3.333333,3.333333,1,3.333333
1206,Rhapsody: A Musical Adventure,True,1,True,True,Role-Playing (RPG),True,NaN,True,67,...,13.200000,16.416667,12.500000,5,11.166667,9.650000,10.933333,9.133333,22,8.066667
1207,Secret Files: Tunguska,True,1,True,True,Adventure,True,NaN,True,71,...,11.500000,11.750000,11.500000,2,11.250000,8.800000,12.566667,8.716667,16,6.816667
1208,Fading Shadows,True,1,True,True,"Action,Adventure",True,NaN,True,62,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1209,Hail to the Chimp,True,1,True,True,"Action,Strategy",True,NaN,True,51,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000
1210,Secret Files: Tunguska,True,2,True,True,Adventure,True,NaN,True,64,...,11.500000,11.750000,11.500000,2,11.250000,8.800000,12.566667,8.716667,16,6.816667
1211,Chicken Hunter,True,1,True,True,Action,True,NaN,True,39,...,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000

### Getting a subset of the main source

In [27]:
mainGameData = game[['Title','Metadata.Genres', 'Metadata.Publishers','Length.Main + Extras.Average','Release.Rating','Release.Year']]
mainGameData

,Title,Metadata.Genres,Metadata.Publishers,Length.Main + Extras.Average,Release.Rating,Release.Year
0,Super Mario 64 DS,Action,Nintendo,24.916667,E,2004
1,Lumines: Puzzle Fusion,Strategy,Ubisoft,9.750000,E,2004
2,WarioWare Touched!,"Action,Racing / Driving,Sgameports",Nintendo,3.850000,E,2004
3,Hot Shots Golf: Open Tee,Sports,Sony,0.000000,E,2004
4,Spider-Man 2,Action,Activision,12.766667,E,2004
5,The Urbz: Sims in the City,Simulation,EA,20.833333,M,2004
6,Ridge Racer,Racing / Driving,Namco,0.883333,E,2004
7,Metal Gear Ac!d,Strategy,Konami,24.833333,E,2004
8,Madden NFL 2005,Sports,EA,0.000000,T,2004
9,Pokmon Dash,Racing / Driving,Nintendo,0.000000,T,2004
10,Dynasty Warriors,"Action,Adventure,Role-Playing (RPG)",NaN,0.000000,E,2004
11,Feel the Magic XY/XX,"Action,Adventure,Racing / Driving,Sports",Sega,3.100000,T,2004
12,Ridge Racer DS,Racing / Driving,Namco,0.000000,E,2004
13,Darkstalkers Chronicle: The Chaos Tower,Action,Capcom,0.000000,E,2004
14,Ape Escape Academy,"Action,Sports",Sony,0.000000,E,2004
15,Polarium,Strategy,Nintendo,0.000000,E,2004
16,Asphalt: Urban GT,"Racing / Driving,Simulation",Ubisoft,0.000000,E,2004
17,Zoo Keeper,Action,NaN,0.000000,T,2004
18,Mr. DRILLER: Drill Spirits,Action,Namco,0.000000,T,2004
19,Sprung,Adventure,Ubisoft,0.000000,E,2004
20,Armored Core: Formula Front - Extreme Battle,"Action,Strategy",NaN,0.000000,E,2004
21,Puyo Pop Fever,"Action,Strategy",Sega,4.000000,E,2004
22,Mario Kart DS,Racing / Driving,Nintendo,10.716667,E,2005
23,Nintendogs,Simulation,Nintendo,43.350000,E,2005
24,Brain Age: Train Your Brain in Minutes a Day!,Action,Nintendo,0.933333,M,2005
25,Brain Agey: More Training in Minutes a Day!,Action,Nintendo,23.333333,E,2005
26,Grand Theft Auto: Liberty City Stories,"Action,Racing / Driving","Capcom,Rockstar",26.550000,E,2005
27,Animal Crossing: Wild World,Simulation,Nintendo,180.533333,T,2005
28,Big Brain Academy,Action,Nintendo,8.066667,E,2005
29,Call of Duty 2,Action,"Activision,Konami",9.600000,E,2005
...,...,...,...,...,...,...
1182,Harvey Birdman: Attorney at Law,Adventure,Capcom,0.000000,M,2008
1183,Secret Agent Clank,Action,Sony,7.850000,M,2008
1184,Space Invaders Extreme,Action,SquareEnix,0.000000,M,2008
1185,Armored Core: For Answer,Action,Ubisoft,17.266667,M,2008
1186,Legendary,Action,Atari,7.600000,E,2008
1187,Agatha Christie: Evil Under the Sun,Adventure,NaN,0.000000,M,2008
1188,Agatha Christie: And Then There Were None,Adventure,NaN,0.000000,M,2008
1189,Armored Core: For Answer,Action,Ubisoft,17.266667,T,2008
1190,Cradle of Rome,Strategy,NaN,0.000000,E,2008
1191,The Dark Spire,"Adventure,Role-Playing (RPG)",NaN,76.816667,T,2008
1192,"Flower, Sun and Rain",Adventure,NaN,8.816667,M,2008
1193,Insecticide,"Action,Adventure",NaN,3.083333,T,2008
1194,Izuna 2: The Unemployed Ninja Returns,Role-Playing (RPG),NaN,0.000000,E,2008
1195,Looney Tunes: Cartoon Conductor,Action,Eidos,0.000000,M,2008
1196,Nanostray 2,Action,NaN,0.000000,M,2008
1197,Hellboy: The Science of Evil,Action,Konami,0.000000,E,2008
1198,Pipe Mania,Strategy,NaN,0.000000,T,2008
1199,UEFA Euro 2008,Sports,EA,0.000000,E,2008
1200,Vampire Rain,Action,NaN,0.000000,E,2008
1201,Baroque,"Action,Role-Playing (RPG)",NaN,0.000000,T,2008
1202,Supreme Commander,Strategy,NaN,26.266667,T,2008
1203,Hail to the Chimp,"Action,Strategy",NaN,0.000000,M,2008
1204,Assassin's Creed: Altar's Chronicles,Action,Ubisoft,4.516667,T,2008
1205,The Legend of Kage 2,Action,SquareEnix,0.000000,E,2008
1206,Rhapsody: A Musical Adventure,Role-Playing (RPG),NaN,13.200000,M,2008
1207,Secret Files: Tunguska,Adventure,NaN,11.500000,M,2008
1208,Fading Shadows,"Action,Adventure",NaN,0.000000,E,2008
1209,Hail to the Chimp,"Action,Strategy",NaN,0.000000,M,2008
1210,Secret Files: Tunguska,Adventure,NaN,11.500000,M,2008
1211,Chicken Hunter,Action,NaN,0.000000,T,2008

## Get the publisher values

In [30]:
#publishers
publisher  = list(set(mainGameData['Metadata.Publishers'].tolist()))
publisher

[nan,
 'Microsoft,SquareEnix',
 'Nintendo,SquareEnix',
 '2K',
 'THQ',
 'Namco,Sony',
 'EA,Sony',
 'Midway',
 'Sony,Ubisoft',
 'Microsoft',
 'Disney',
 'Konami',
 'SquareEnix',
 'Namco,Ubisoft',
 'Ubisoft',
 'Atari',
 'Capcom,Rockstar',
 'Capcom',
 'Activision,Konami',
 'Atari,Namco',
 'Eidos',
 'Capcom,Nintendo',
 'Nintendo',
 'EA,Namco',
 'Sega',
 'Rockstar',
 'Activision',
 'Namco',
 'Sony',
 'Activision,Sony',
 'EA',
 'Nintendo,Sega']

## Get the genre values

In [7]:
#Genre
genre  = list(set(mainGameData['Metadata.Genres'].tolist()))
genre

['Role-Playing (RPG),Simulation',
 'Simulation,Sports',
 'Action,Adventure,Racing / Driving',
 'Racing / Driving,Sports',
 'Action,Role-Playing (RPG),Strategy',
 'Racing / Driving,Simulation,Strategy',
 'Adventure',
 'Simulation',
 'Action,Strategy',
 'Strategy',
 'Action',
 'Action,Adventure',
 'Action,Role-Playing (RPG),Simulation',
 'Action,Adventure,Strategy',
 'Role-Playing (RPG),Strategy',
 'Adventure,Role-Playing (RPG),Strategy',
 'Action,Racing / Driving,Role-Playing (RPG),Strategy',
 'Action,Adventure,Role-Playing (RPG)',
 'Educational,Strategy',
 'Simulation,Strategy',
 'Action,Adventure,Racing / Driving,Sports',
 'Educational,Sports',
 'Action,Role-Playing (RPG)',
 'Role-Playing (RPG),Simulation,Strategy',
 'Action,Educational',
 'Action,Racing / Driving,Sports',
 'Adventure,Simulation,Sports',
 'Simulation,Sports,Strategy',
 'Action,Racing / Driving,Sgameports',
 'Action,Role-Playing (RPG),Simulation,Sports,Strategy',
 'Action,Simulation',
 'Racing / Driving',
 'Action,Racing / Driving,Sports,Strategy',
 'Action,Racing / Driving',
 'Sports,Strategy',
 'Action,Simulation,Sports',
 'Educational',
 'Adventure,Simulation',
 'Adventure,Role-Playing (RPG)',
 'Action,Racing / Driving,Simulation',
 'Sports',
 'Action,Simulation,Strategy',
 'Racing / Driving,Simulation,Sports',
 'Action,Sports',
 'Adventure,Educational,Strategy',
 'Role-Playing (RPG)',
 'Action,Racing / Driving,Role-Playing (RPG)',
 'Educational,Simulation',
 'Racing / Driving,Simulation']

In [8]:
def genreStrToList(genreStr):
    genreList = genreStr.split(',')
    return genreList

In [9]:
genreStrToList(genre[3])

['Racing / Driving', 'Sports']

In [10]:
extGenreList =list(map(genreStrToList, genre)) 
extGenreList

[['Role-Playing (RPG)', 'Simulation'],
 ['Simulation', 'Sports'],
 ['Action', 'Adventure', 'Racing / Driving'],
 ['Racing / Driving', 'Sports'],
 ['Action', 'Role-Playing (RPG)', 'Strategy'],
 ['Racing / Driving', 'Simulation', 'Strategy'],
 ['Adventure'],
 ['Simulation'],
 ['Action', 'Strategy'],
 ['Strategy'],
 ['Action'],
 ['Action', 'Adventure'],
 ['Action', 'Role-Playing (RPG)', 'Simulation'],
 ['Action', 'Adventure', 'Strategy'],
 ['Role-Playing (RPG)', 'Strategy'],
 ['Adventure', 'Role-Playing (RPG)', 'Strategy'],
 ['Action', 'Racing / Driving', 'Role-Playing (RPG)', 'Strategy'],
 ['Action', 'Adventure', 'Role-Playing (RPG)'],
 ['Educational', 'Strategy'],
 ['Simulation', 'Strategy'],
 ['Action', 'Adventure', 'Racing / Driving', 'Sports'],
 ['Educational', 'Sports'],
 ['Action', 'Role-Playing (RPG)'],
 ['Role-Playing (RPG)', 'Simulation', 'Strategy'],
 ['Action', 'Educational'],
 ['Action', 'Racing / Driving', 'Sports'],
 ['Adventure', 'Simulation', 'Sports'],
 ['Simulation', 'Sports', 'Strategy'],
 ['Action', 'Racing / Driving', 'Sgameports'],
 ['Action', 'Role-Playing (RPG)', 'Simulation', 'Sports', 'Strategy'],
 ['Action', 'Simulation'],
 ['Racing / Driving'],
 ['Action', 'Racing / Driving', 'Sports', 'Strategy'],
 ['Action', 'Racing / Driving'],
 ['Sports', 'Strategy'],
 ['Action', 'Simulation', 'Sports'],
 ['Educational'],
 ['Adventure', 'Simulation'],
 ['Adventure', 'Role-Playing (RPG)'],
 ['Action', 'Racing / Driving', 'Simulation'],
 ['Sports'],
 ['Action', 'Simulation', 'Strategy'],
 ['Racing / Driving', 'Simulation', 'Sports'],
 ['Action', 'Sports'],
 ['Adventure', 'Educational', 'Strategy'],
 ['Role-Playing (RPG)'],
 ['Action', 'Racing / Driving', 'Role-Playing (RPG)'],
 ['Educational', 'Simulation'],
 ['Racing / Driving', 'Simulation']]

In [11]:
genre1D = []
for genreRow in extGenreList:
    genre1D.extend(genreRow)
    
genre1D = list(set(genre1D))
genre1D

['Strategy',
 'Racing / Driving',
 'Sgameports',
 'Adventure',
 'Educational',
 'Simulation',
 'Action',
 'Sports',
 'Role-Playing (RPG)']

## Creating a class that will make the different insert operations

In [144]:
import random
from datetime import datetime, timedelta

In [195]:
class sqlProjectCreator:
    def createGenreInsert(self, values):
        valuesStr = list(map(lambda x: "('%s')"%x, values ))
        insertStmt = 'INSERT INTO TBL_GENRE values %s ;' % (",".join(valuesStr))
        return insertStmt
    
    def createCategoryInsert(self, values):
        valuesStr = list(map(lambda x: "('%s')"%x, values ))
        insertStmt = 'INSERT INTO TBL_CATEGORY values %s ;' % (",".join(valuesStr))
        return insertStmt
    
    def createDevInsert(self, values):
        valuesStr = list(map(lambda x: "('%s')"%x, values ))
        insertStmt = 'INSERT INTO TBL_DEVELOPER values %s ;' % (",".join(valuesStr))
        return insertStmt


    def createGameInsert(self, games, publisherList):

        gameParseList = []
        for index, game in games.iterrows():
            name = game['Title']
            if '\'' in name: continue
            
            release_date = game['Release.Year']
            duration = int(game['Length.Main + Extras.Average'])
            if(duration == 0):  duration = 1
            dev_id = publisher.index(game['Metadata.Publishers']) + 1
            cat_id = game['Release.Rating']
            
            
    def createGameGenreInsert(self, myGameTable, gameSource):
        genreDict = {'Adventure':6,'Sgameports':9,'Sports':8,'Racing / Driving':2,'Action':3,'Educational':1,'Simulation':5,'Role-Playing (RPG)':4,'Strategy':7}    
        genreInsertValues = []
        
        for index, game in myGameTable.iterrows():
            name = game['GM_NAME']
            sourceRow = gameSource.loc[gameSource['Title'] == name]
            genreList = sourceRow['Metadata.Genres'].tolist()
            genreList = genreList[0].split(',')
            
            for genre in genreList:
                
                genreValue = "(%s, %s)" % (game['GM_ID'], genreDict[genre])
                genreInsertValues.append(genreValue)
            
        
        insertStmt = 'INSERT INTO TBL_GAME_GENRE VALUES %s ;' % (",".join(genreInsertValues))
        return insertStmt
            
    def CreateCatalogueInsert(self, myGameTable, catalogueList):
        catalogueInsertValues = []
        
        for index, game in myGameTable.iterrows():
            catalogueRow = catalogueList.loc[catalogueList['GM_ID'] == game['GM_ID']]
            catalogueDiscount = catalogueRow["DISCOUNT"]
            catalogueInsertValues.append('( %s, %s )' % (float(catalogueDiscount), int(game['GM_ID'])))
            
        insertStmt = 'INSERT INTO TBL_CATALOGUE VALUES %s ;' % (",".join(catalogueInsertValues))
        return insertStmt
    
    def CreateUserInsert(self, userTable):
        userInsertValues = []
        
        for index, user in userTable.iterrows():
            username = user['USERNAME']
            email = user['EMAIL']
            pw = user['PASSWORD'] 
            playing = user['IS_PLAYING']
            
            userValue = "\n\t( '%s', '%s', '%s', %s )" % (username, email, pw, int(playing))
            
            userInsertValues.append(userValue)
            
        insertStmt = 'INSERT INTO TBL_USER VALUES %s \n;' % (",".join(userInsertValues))
        return insertStmt
    
    def CreateSaleInsert(self, userTable, catalogueTable):
        
        userRandomSale = []
        count = 0
        for index, user in userTable.iterrows():
            #Crear una lista de compras totales por usuario mediante un numero random entre 0 - 10
            totalSales = random.randint(0, 10)
            
            for sale in range(totalSales):
                 #Seleccionar juegos random 
                randomGame = random.randint(0, catalogueTable.shape[0] - 1)
                rndCatalogueId = catalogueTable.iloc[randomGame]["CATLG_ID"]
                

                #15% de los juegos comprados que sean regalos
                isGift = False
                randomInt = random.randint(1, 20)
                if(randomInt <= 3):
                    isGift = True

                #fechas random pero si son regalos intentar que en un 60% sean el 14/02 o 24/12
                
                inicio = datetime(2013, 1, 1)
                final =  datetime(2020, 12, 31)
                ranDate = inicio + (final - inicio) * random.random()
                
                if(isGift):
                    randomInt = random.randint(1, 20)
                    if(randomInt <= 12):
                        year = random.randint(2013, 2020)
                        day = 24
                        month = 12
                        if(randomInt <=6):
                            day = 14
                            month = 2
                            
                        ranDate = datetime(year, month, day)
                    
                    
                dateStr = '%s/%s/%s' % (ranDate.year, ranDate.month, ranDate.day)
                insertValue = " (%s, %s, '%s', %s)" % (rndCatalogueId, user["USER_ID"], dateStr, int(isGift))    
                if(count%3 == 0):
                    insertValue = "\n\t%s" % insertValue
                count += 1
                userRandomSale.append(insertValue)
            
        insertStmt = 'INSERT INTO TBL_SALE VALUES %s \n;' % (",".join(userRandomSale))
        return insertStmt
    
    def createGiftInsert(self, saleTable, userTable):
        giftInsertValues = []
        giftDict = {}
        count = 0
        for index, sale in saleTable.iterrows():
            if(sale['IS_GIFT']):
                rndUserId = sale['USER_ID']
                while(rndUserId == sale['USER_ID']):
                    randomUser = random.randint(0, userTable.shape[0] - 1)
                    rndUserId = userTable.iloc[randomUser]["USER_ID"]
                
                
                insertValue = "(%s, %s)" % (sale['SALE_ID'], rndUserId)
                giftDict[sale['SALE_ID']] = rndUserId
                if(count%6 == 0):
                    insertValue = "\n\t%s" % insertValue
                giftInsertValues.append(insertValue)
                count += 1
                
        insertStmt = 'INSERT INTO GAME_GIFT VALUES %s \n;' % (",".join(giftInsertValues))
        
        return (insertStmt, giftDict)
            
    def createOwnerInsert(self, saleTable, giftDict, catalogTable):
        ownerInsertValues = []
        count = 0
        for index, sale in saleTable.iterrows():
            ownerId = sale['USER_ID']
            if(sale['IS_GIFT']):
                ownerId = int(giftDict[sale['SALE_ID']])
                
            catalogueRow =  catalogTable[catalogTable['CATLG_ID'] == sale['CATLG_ID']]
            insertValue = "(%s, %s)" % (ownerId, int(catalogueRow['GM_ID']))
            if(count%6 == 0):
                insertValue = "\n\t%s" % insertValue
            ownerInsertValues.append(insertValue)                
            count += 1
            
            
                
        insertStmt = 'INSERT INTO TBL_GAME_OWNER VALUES %s \n;' % (",".join(ownerInsertValues))
        
        return insertStmt
    
    def CreateSessionInsert(self, gameOwner, myGameTable, saleTable, gifts, catalogue):
        
        game_session_values = []
        count = 0
        for index, game_played in gameOwner.iterrows():
            
            #Fecha cuando se obtuvo el juego
            currentGameId = game_played['GM_ID'] 
            catalogueRow = catalogue[catalogue['GM_ID'] == currentGameId]
            catalogueId =int( catalogueRow['CATLG_ID'])
            saleRows = saleTable[saleTable['CATLG_ID'] == catalogueId]
            rowExist = saleRows[saleRows['USER_ID'] == game_played['USER_ID']]


            #OBTENER VENTA DEL JUEGO  Y fECHA DE COMPRA
            if (not rowExist.empty and rowExist.empty == False ):
                saleRowFound = rowExist
            else:
                for index, saleRow in saleRows.iterrows():
                    saleId = saleRow['SALE_ID']
                    if saleId in gifts:
                        if (gifts[saleId] == game_played['USER_ID']):
                            saleRowFound = saleRow
                    else:
                        continue
                    
            #session inicial 
            fecha_sql = saleRowFound['SALE_DATE']
            fechaStr = fecha_sql                
            if(not type(fecha_sql) == str):
                fecha_sql = fecha_sql.tolist()
                fechaStr = fecha_sql[0]
                
            
            fecha_inicio = datetime.strptime(fechaStr, '%Y-%m-%d %H:%M:%S')
            fecha_final =  datetime(2021, 3, 25)                
            ranDate = fecha_inicio + (fecha_final - fecha_inicio) * random.random()    
            dateStr = '%s/%s/%s' % (ranDate.year, ranDate.month, ranDate.day)
                
            
            #Crear una lista de sesiones totales por juego del usuario mediante un numero random entre 0 - 10
            prox_inicio = ranDate
            totalSessions = random.randint(0, 3)
            for session in range(totalSessions):
                inicio = prox_inicio
                hours = 8
                hours_added = timedelta(hours = hours)
                fecha_final_limite =  inicio + hours_added
                final = inicio + (fecha_final_limite - inicio) * random.random()    
                delta = final - inicio
                horasDeJuego = (round(delta.total_seconds() / 3600.0 ,2))
                
                
                insertValue = "(%s, %s, %s, '%s', '%s')" % (
                    game_played['USER_ID'],
                    game_played['GM_ID'],
                    horasDeJuego ,
                    inicio.strftime("%Y/%m/%d %H:%M:%S"),
                    final.strftime("%Y/%m/%d %H:%M:%S"),
                )
                 
                if(count%3 == 0):
                    insertValue = "\n\t%s" % insertValue
                
                game_session_values.append(insertValue)
                count += 1
                
                
    
        insertStmt = 'INSERT INTO TBL_GAME_SESSION VALUES %s \n;' % (",".join(game_session_values))
        return insertStmt
        
        
#instance of the class
        
sqlPro = sqlProjectCreator()

## Genres insert operations

In [14]:
sqlPro.createGenreInsert(genre1D)

"INSERT INTO TBL_GENRE values ('Strategy'),('Racing / Driving'),('Sgameports'),('Adventure'),('Educational'),('Simulation'),('Action'),('Sports'),('Role-Playing (RPG)') ;"

## Developers insert operations

In [15]:
sqlPro.createDevInsert(publisher)

"INSERT INTO TBL_DEVELOPER values ('nan'),('Microsoft,SquareEnix'),('Nintendo,SquareEnix'),('2K'),('THQ'),('Namco,Sony'),('EA,Sony'),('Midway'),('Sony,Ubisoft'),('Microsoft'),('Disney'),('Konami'),('SquareEnix'),('Namco,Ubisoft'),('Ubisoft'),('Atari'),('Capcom,Rockstar'),('Capcom'),('Activision,Konami'),('Atari,Namco'),('Eidos'),('Capcom,Nintendo'),('Nintendo'),('EA,Namco'),('Sega'),('Rockstar'),('Activision'),('Namco'),('Sony'),('Activision,Sony'),('EA'),('Nintendo,Sega') ;"

## Game and Genre relation insert operations

In [33]:
txt = sqlPro.createGameInsert(mainGameData, publisher)
f = open('gameInsert.sql', 'w')
f.write(txt)
f.close()

None

In [28]:
myGameTable = pd.read_csv('data/myGameTable.csv')
myGameTable

,GM_ID,GM_NAME,RELEASE_DATE,ESTM_DURATION,DEV_ID,CAT_CODE
0,1,Super Mario 64 DS,2004-12-13 00:00:00,24,10,E
1,2,Lumines: Puzzle Fusion,2004-12-13 00:00:00,9,9,E
2,3,WarioWare Touched!,2004-12-13 00:00:00,3,10,E
3,4,Hot Shots Golf: Open Tee,2004-12-13 00:00:00,1,6,E
4,5,Spider-Man 2,2004-12-13 00:00:00,12,11,E
5,6,The Urbz: Sims in the City,2004-12-13 00:00:00,20,31,M
6,7,Ridge Racer,2004-12-13 00:00:00,1,4,E
7,8,Metal Gear Ac!d,2004-12-13 00:00:00,24,24,E
8,9,Madden NFL 2005,2004-12-13 00:00:00,1,31,T
9,10,Pokmon Dash,2004-12-13 00:00:00,1,10,T
10,11,Dynasty Warriors,2004-12-13 00:00:00,1,1,E
11,12,Feel the Magic XY/XX,2004-12-13 00:00:00,3,5,T
12,13,Ridge Racer DS,2004-12-13 00:00:00,1,4,E
13,14,Darkstalkers Chronicle: The Chaos Tower,2004-12-13 00:00:00,1,27,E
14,15,Ape Escape Academy,2004-12-13 00:00:00,1,6,E
15,16,Polarium,2004-12-13 00:00:00,1,10,E
16,17,Asphalt: Urban GT,2004-12-13 00:00:00,1,9,E
17,18,Zoo Keeper,2004-12-13 00:00:00,1,1,T
18,19,Mr. DRILLER: Drill Spirits,2004-12-13 00:00:00,1,4,T
19,20,Sprung,2004-12-13 00:00:00,1,9,E
20,21,Armored Core: Formula Front - Extreme Battle,2004-12-13 00:00:00,1,1,E
21,22,Puyo Pop Fever,2004-12-13 00:00:00,4,5,E
22,23,Mario Kart DS,2005-12-13 00:00:00,10,10,E
23,24,Nintendogs,2005-12-13 00:00:00,43,10,E
24,25,Brain Age: Train Your Brain in Minutes a Day!,2005-12-13 00:00:00,1,10,M
25,26,Brain Agey: More Training in Minutes a Day!,2005-12-13 00:00:00,23,10,E
26,27,Grand Theft Auto: Liberty City Stories,2005-12-13 00:00:00,26,29,E
27,28,Animal Crossing: Wild World,2005-12-13 00:00:00,180,10,T
28,29,Big Brain Academy,2005-12-13 00:00:00,8,10,E
29,30,Call of Duty 2,2005-12-13 00:00:00,9,14,E
...,...,...,...,...,...,...
62,63,Condemned: Criminal Origins,2005-12-13 00:00:00,9,5,E
63,64,Castlevania: Dawn of Sorrow,2005-12-13 00:00:00,15,24,T
64,65,SpongeBob SquarePants: The Yellow Avenger,2005-12-13 00:00:00,1,18,E
65,66,Marvel Nemesis: Rise of the Imperfects,2005-12-13 00:00:00,6,31,T
66,67,Kameo: Elements of Power,2005-12-13 00:00:00,11,20,T
67,68,Advance Wars: Dual Strike,2005-12-13 00:00:00,73,10,T
68,69,Trauma Center: Under the Knife,2005-12-13 00:00:00,11,10,T
69,70,Coded Arms,2005-12-13 00:00:00,8,24,M
70,71,NBA LIVE 06,2005-12-13 00:00:00,1,31,E
71,72,Star Wars: Episode III - Revenge of the Sith,2005-12-13 00:00:00,5,9,E
72,73,Capcom Classics Collection Remixed,2005-12-13 00:00:00,35,27,E
73,74,Madagascar,2005-12-13 00:00:00,9,11,E
74,75,X-Men: Legends II - Rise of Apocalypse,2005-12-13 00:00:00,21,11,M
75,76,Quake 4,2005-12-13 00:00:00,10,11,E
76,77,Pokmon Trozei!,2005-12-13 00:00:00,1,10,E
77,78,Need for Speed: Most Wanted,2005-12-13 00:00:00,15,31,E
78,79,Mega Man Maverick Hunter X,2005-12-13 00:00:00,8,27,E
79,80,Metroid Prime Pinball,2005-12-13 00:00:00,5,10,E
80,120,Donkey Kong Barrel Blast,2007-12-13 00:00:00,1,10,T
81,121,The BIGS,2007-12-13 00:00:00,1,7,M
82,122,Armored Core 4,2007-12-13 00:00:00,19,5,E
83,123,Etrian Odyssey,2007-12-13 00:00:00,58,10,E
84,124,Ben 10: Protector of the Earth,2007-12-13 00:00:00,5,1,T
85,125,Looney Tunes: Acme Arsenal,2007-12-13 00:00:00,1,1,T
86,126,Pokmon Ranger: Shadows of Almia,2008-12-13 00:00:00,27,10,T
87,127,Mortal Kombat vs. DC Universe,2008-12-13 00:00:00,7,16,M
88,128,Dead Space,2008-12-13 00:00:00,13,31,M
89,129,Shaun White Snowboarding: Road Trip,2008-12-13 00:00:00,1,9,E
90,130,Star Wars: The Force Unleashed,2008-12-13 00:00:00,8,1,E
91,131,Guitar Hero: Aerosmith,2008-12-13 00:00:00,27,11,E

In [18]:
genre = sqlPro.createGameGenreInsert(myGameTable, mainGameData)
genre

'INSERT INTO TBL_GAME_GENRE VALUES (1, 3),(2, 7),(3, 3),(3, 2),(3, 9),(4, 8),(5, 3),(6, 5),(7, 2),(8, 7),(9, 8),(10, 2),(11, 3),(11, 6),(11, 4),(12, 3),(12, 6),(12, 2),(12, 8),(13, 2),(14, 3),(15, 3),(15, 8),(16, 7),(17, 2),(17, 5),(18, 3),(19, 3),(20, 6),(21, 3),(21, 7),(22, 3),(22, 7),(23, 2),(24, 5),(25, 3),(26, 3),(27, 3),(27, 2),(28, 5),(29, 3),(30, 3),(31, 2),(32, 2),(33, 4),(34, 3),(35, 3),(36, 3),(37, 2),(38, 5),(38, 7),(39, 4),(39, 5),(40, 3),(40, 4),(41, 8),(42, 2),(43, 3),(43, 2),(44, 3),(45, 3),(46, 3),(47, 3),(47, 2),(48, 8),(49, 7),(50, 3),(50, 4),(51, 4),(51, 5),(52, 3),(52, 2),(53, 8),(54, 3),(54, 8),(55, 3),(56, 6),(56, 5),(57, 3),(58, 8),(59, 3),(60, 3),(61, 3),(62, 8),(63, 3),(63, 6),(64, 3),(64, 4),(65, 3),(66, 3),(67, 3),(68, 7),(69, 3),(69, 5),(70, 3),(71, 8),(72, 3),(73, 3),(74, 6),(75, 3),(75, 4),(76, 3),(77, 7),(78, 2),(79, 3),(80, 3),(80, 5),(120, 2),(121, 3),(121, 5),(121, 8),(122, 3),(123, 4),(124, 3),(125, 3),(126, 3),(126, 4),(127, 3),(128, 3),(129, 8),(130, 3),(131, 3),(131, 5) ;'

## Catalogue insert operations

In [19]:
catalogueTable = pd.read_csv('data/catalogue.csv')
catalogueTable

     DISCOUNT  GM_ID
0         0.3      1
1         0.3      2
2         0.0      3
3         0.3      4
4         0.2      5
..        ...    ...
126       0.5    127
127       0.0    128
128       0.4    129
129       0.4    130
130       0.1    131

[131 rows x 2 columns]

In [20]:
catalogue = sqlPro.CreateCatalogueInsert(myGameTable, catalogueTable)
catalogue

'INSERT INTO TBL_CATALOGUE VALUES ( 0.3, 1 ),( 0.3, 2 ),( 0.0, 3 ),( 0.3, 4 ),( 0.2, 5 ),( 0.0, 6 ),( 0.2, 7 ),( 0.2, 8 ),( 0.4, 9 ),( 0.5, 10 ),( 0.0, 11 ),( 0.2, 12 ),( 0.2, 13 ),( 0.5, 14 ),( 0.1, 15 ),( 0.5, 16 ),( 0.1, 17 ),( 0.5, 18 ),( 0.1, 19 ),( 0.3, 20 ),( 0.5, 21 ),( 0.1, 22 ),( 0.3, 23 ),( 0.5, 24 ),( 0.5, 25 ),( 0.1, 26 ),( 0.5, 27 ),( 0.3, 28 ),( 0.2, 29 ),( 0.2, 30 ),( 0.6, 31 ),( 0.3, 32 ),( 0.4, 33 ),( 0.6, 34 ),( 0.6, 35 ),( 0.5, 36 ),( 0.2, 37 ),( 0.2, 38 ),( 0.5, 39 ),( 0.2, 40 ),( 0.2, 41 ),( 0.2, 42 ),( 0.1, 43 ),( 0.1, 44 ),( 0.6, 45 ),( 0.4, 46 ),( 0.4, 47 ),( 0.5, 48 ),( 0.2, 49 ),( 0.2, 50 ),( 0.1, 51 ),( 0.5, 52 ),( 0.4, 53 ),( 0.1, 54 ),( 0.5, 55 ),( 0.6, 56 ),( 0.5, 57 ),( 0.5, 58 ),( 0.1, 59 ),( 0.5, 60 ),( 0.2, 61 ),( 0.2, 62 ),( 0.2, 63 ),( 0.5, 64 ),( 0.2, 65 ),( 0.3, 66 ),( 0.5, 67 ),( 0.4, 68 ),( 0.2, 69 ),( 0.2, 70 ),( 0.1, 71 ),( 0.2, 72 ),( 0.2, 73 ),( 0.0, 74 ),( 0.5, 75 ),( 0.2, 76 ),( 0.4, 77 ),( 0.1, 78 ),( 0.2, 79 ),( 0.2, 80 ),( 0.2, 120 ),( 0.0, 121 ),( 0.2, 122 ),( 0.5, 123 ),( 0.5, 124 ),( 0.1, 125 ),( 0.2, 126 ),( 0.5, 127 ),( 0.0, 128 ),( 0.4, 129 ),( 0.4, 130 ),( 0.1, 131 ) ;'

## User Insert Operations

In [21]:
userTable = pd.read_csv('data/Users.csv')
userTable

,USERNAME,EMAIL,PASSWORD,IS_PLAYING
0,ihedden0,jposthill0@apple.com,Z4ANou,1
1,ocarlyon1,tyouel1@weibo.com,VPaP6zqzEUm,0
2,sbassilashvili2,rminchella2@chron.com,MPHZ5Rk,1
3,rsiddaley3,akinze3@drupal.org,gfXXC0p5kHw,1
4,tjannex4,rrogge4@vk.com,tOFVq5CLeeWd,0
5,ghugonin5,jgrishunin5@npr.org,MbT02Jty5vix,0
6,grisborough6,ccawcutt6@prweb.com,T1nm1Lo9xuQz,1
7,treddlesden7,oeasen7@drupal.org,fzj76JSYiCyV,1
8,enortcliffe8,jdey8@github.io,SNSchM,1
9,mgyles9,odomb9@hubpages.com,9pxpmOcUYQ65,1
10,rwidgera,hlaugharnea@bloglovin.com,jeR58kcrl,0
11,ngoatmanb,ntregianb@so-net.ne.jp,HjLU12zQO,0
12,gclemencec,gmctrustriec@ucsd.edu,pbOS7dGAyk90,0
13,csymmsd,dgiacomazzod@samsung.com,dmjICvdoYM,0
14,epuviae,hharvisone@de.vu,S0gATut,0
15,kpallentf,gfayersf@indiatimes.com,7bfjF9Je0pY,1
16,wmcclareng,ljorckg@techcrunch.com,DRkkTL2c4o,1
17,cboarleysonh,etallh@goo.gl,wQAqwn,1
18,amynardi,eazami@mapquest.com,gCdzUwek3,0
19,santoniasj,dcriellyj@networksolutions.com,gE64xakb3RtR,1
20,sbrookesk,egerdesk@imageshack.us,sGagtE,0
21,scarnoghanl,tlenniel@bloglines.com,r0VZKgzF,0
22,ebazellem,aolenanem@xinhuanet.com,0Gsmfkt8Ob04,0
23,aohenecann,rluchellin@joomla.org,6cdWg3QXnd,1
24,aleveretteo,atethero@youtu.be,6plDTb882k,1
25,mwharbyp,wblaydesp@xing.com,DhBgRuRpa,0
26,bphorsbyq,kbasketterq@harvard.edu,kh2FVJHw,1
27,jscroggier,ltabernerr@microsoft.com,hVP3rXcXdU,0
28,escares,kdrakes@cdc.gov,m4OXy4y0m,0
29,mlobliet,moffillt@hugedomains.com,NN8EhaHZNCJ,0
...,...,...,...,...
70,blobe1y,amorfield1y@google.com.hk,rsP1yqIzY4,1
71,bdonner1z,mhartropp1z@yelp.com,F50GaYkf2t2,0
72,dfoxhall20,mstanlack20@toplist.cz,eddeywXUq,1
73,gwilcott21,rsalvadore21@1und1.de,NwioMVutNox,0
74,dthiolier22,cmartyns22@mail.ru,S93C0eV,0
75,kagglione23,rcapun23@reverbnation.com,rt0t9mZd4,1
76,labbatt24,tharvard24@flickr.com,NANynYaIta,1
77,eoshaughnessy25,ddavoren25@sphinn.com,QwpjsUxWidhT,1
78,jmizzen26,psyrett26@spotify.com,ZWPhcaT,1
79,cweich27,jlipman27@hp.com,WqKzBK,0
80,troloff28,jrego28@archive.org,1Aew3Nt,1
81,pboyen29,lcrumbleholme29@feedburner.com,NpoHKXS89XV,1
82,cogg2a,jnand2a@dmoz.org,sjYD52,1
83,pwem2b,tneal2b@csmonitor.com,m29chDqOKh,0
84,medgeworth2c,jjude2c@apache.org,hgYBykF,0
85,djardine2d,hyven2d@intel.com,WETz7E,1
86,frichard2e,speddowe2e@scribd.com,nWzx6mNy1IYB,0
87,cgaffney2f,mphette2f@taobao.com,FFvzVXr8E,0
88,kablett2g,cfarragher2g@pinterest.com,yrBHsnKq,0
89,mgregoratti2h,ggulleford2h@wikipedia.org,LAkEVxqv75Xd,1
90,bfido2i,tleeuwerink2i@examiner.com,wg77lz10W,1
91,nbasey2j,mpallasch2j@gov.uk,DI8IKeex1,0
92,pguillet2k,gnorrie2k@theglobeandmail.com,oOy6BaNI,0
93,lcholdcroft2l,znelson2l@google.ca,iC2mGcujcl,1
94,swadeling2m,uledington2m@pcworld.com,jwKkiPS6lJJ,0
95,gwinny2n,rblaver2n@bandcamp.com,lNHY7330,1
96,dmcvitty2o,jdinning2o@creativecommons.org,E2qGshZU,1
97,tdanilevich2p,kwilleson2p@un.org,H0FRjiHAV,1
98,hfulle2q,ztrewinnard2q@simplemachines.org,J538RSP,0
99,kphizackerly2r,mromaynes2r@macromedia.com,YJVoIscZ,0

In [205]:
user = sqlPro.CreateUserInsert(userTable)
f = open('insertUsers.sql', 'w')
f.write(user)
f.close()

## Sale insert Operations

In [250]:
catalogueTable = pd.read_csv('data/tableCatalogue.csv')
catalogueTable

    CATLG_ID  DISCOUNT  GM_ID
0          1       0.3      1
1         82       0.3      2
2         83       0.0      3
3         84       0.3      4
4         85       0.2      5
..       ...       ...    ...
87       168       0.5    127
88       169       0.0    128
89       170       0.4    129
90       171       0.4    130
91       172       0.1    131

[92 rows x 3 columns]

In [220]:
userTable = pd.read_csv('data/userTable.csv')
sale = sqlPro.CreateSaleInsert(userTable, catalogueTable)
f = open('insertSales.sql', 'w')
f.write(sale)
f.close()

## Game Gift insert Operations

In [248]:
saleTable = pd.read_csv('data/SaleTable.csv')
gift, giftDict = sqlPro.createGiftInsert(saleTable, userTable)
f = open('insertGift.sql', 'w')
f.write(gift)
f.close()

In [257]:
giftDict

{6: 6,
 11: 41,
 13: 93,
 15: 54,
 20: 63,
 30: 4,
 35: 2,
 40: 77,
 43: 55,
 44: 33,
 51: 65,
 53: 59,
 75: 55,
 80: 7,
 83: 82,
 84: 87,
 95: 39,
 96: 75,
 100: 54,
 111: 22,
 112: 58,
 113: 98,
 122: 3,
 133: 38,
 144: 56,
 147: 13,
 152: 42,
 160: 60,
 175: 79,
 179: 43,
 182: 84,
 183: 44,
 185: 42,
 205: 94,
 213: 79,
 216: 57,
 219: 25,
 225: 82,
 238: 88,
 239: 61,
 242: 32,
 266: 57,
 278: 96,
 293: 25,
 303: 9,
 306: 43,
 316: 92,
 322: 41,
 323: 98,
 334: 5,
 338: 100,
 342: 52,
 359: 41,
 367: 92,
 376: 28,
 380: 42,
 384: 19,
 406: 15,
 414: 60,
 416: 14,
 424: 23,
 437: 13,
 461: 5,
 462: 81,
 464: 31,
 465: 21}

## Game Owner insert operations

In [262]:
owner = sqlPro.createOwnerInsert(saleTable, giftDict, catalogueTable)
f = open('insertOwner.sql', 'w')
f.write(owner)
f.close()

## Game Session insert Operation

In [5]:
gifts = {
    6: 6, 11: 41, 13: 93, 15: 54, 20: 63, 30: 4,35: 2,
    40: 77, 43: 55, 44: 33, 51: 65, 53: 59, 75: 55,
    80: 7, 83: 82, 84: 87, 95: 39, 96: 75, 100: 54, 111: 22,
    112: 58, 113: 98, 122: 3, 133: 38, 144: 56, 147: 13, 152: 42,
    160: 60, 175: 79, 179: 43, 182: 84, 183: 44, 185: 42, 205: 94,
    213: 79, 216: 57, 219: 25, 225: 82, 238: 88, 239: 61, 242: 32,
    266: 57, 278: 96, 293: 25, 303: 9, 306: 43, 316: 92, 322: 41,
    323: 98, 334: 5, 338: 100, 342: 52, 359: 41, 367: 92, 376: 28,
    380: 42, 384: 19, 406: 15, 414: 60, 416: 14, 424: 23, 437: 13,
    461: 5, 462: 81, 464: 31, 465: 21
 }

In [21]:
game_Owner = pd.read_csv('data/Game_Owner.csv')
myGameTable = pd.read_csv('data/myGameTable.csv')
catalogueTable = pd.read_csv('data/tableCatalogue.csv')
saleTable = pd.read_csv('data/SaleTable.csv')
game_Owner

     GM_OWNER_ID  USER_ID  GM_ID
0              1        1     43
1              2        1     22
2              3        1     28
3              4        1     64
4              5        1     11
..           ...      ...    ...
475          476      100     50
476          477      100     47
477          478      100    129
478          479      100      4
479          480      100     31

[480 rows x 3 columns]

In [30]:
saleTable

     SALE_ID  CATLG_ID  USER_ID            SALE_DATE  IS_GIFT
0          1       123        1  2017-03-28 00:00:00    False
1          2       102        1  2016-01-23 00:00:00    False
2          3       108        1  2013-01-05 00:00:00    False
3          4       144        1  2020-02-10 00:00:00    False
4          5        91        1  2015-01-10 00:00:00    False
..       ...       ...      ...                  ...      ...
475      476       130      100  2018-10-23 00:00:00    False
476      477       127      100  2013-06-06 00:00:00    False
477      478       170      100  2014-01-11 00:00:00    False
478      479        84      100  2017-11-02 00:00:00    False
479      480       111      100  2017-04-06 00:00:00    False

[480 rows x 5 columns]

In [196]:
session= sqlPro.CreateSessionInsert(game_Owner, myGameTable, saleTable, gifts, catalogueTable)
f = open('insertSession.sql', 'w')
f.write(session)
f.close()

In [163]:
gifts[73]

KeyError: 73